FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
COPY .env .
COPY faiss_index_openagenda.idx .
COPY metadata_openagenda.pkl .
COPY app/ ./app/
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install streamlit
EXPOSE 8501
CMD ["streamlit", "run", "app/app_streamlit.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
