FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
COPY .env .
COPY faiss_index_openagenda.idx .
COPY metadata_openagenda.pkl .
COPY app/ ./app/
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
